# Generated by Django 4.2.30 on 2026-07-01 17:42

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_location_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='HotspotId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='HotspotUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('code', models.CharField(db_column='HotspotCode', max_length=50, unique=True)),
                ('name', models.CharField(db_column='HotspotName', max_length=100)),
                ('description', models.TextField(blank=True, db_column='HotspotDescription', null=True)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
                ('village', models.OneToOneField(db_column='VillageId', limit_choices_to={'type': 'V'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotspot', to='location.location')),
            ],
            options={
                'db_table': 'tblHotspots',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
    ]
