# Generated by Django 4.2.30 on 2026-07-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_hotspot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hotspot',
            constraint=models.UniqueConstraint(condition=models.Q(('validity_to__isnull', True)), fields=('village',), name='unique_active_hotspot_village'),
        ),
    ]
