# Generated by Django 4.2.30 on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0023_hotspot_unique_active_hotspot_village"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotspot",
            name="json_ext",
            field=models.JSONField(blank=True, db_column="JsonExt", null=True),
        ),
    ]
