# Generated by Django 4.2.26 on 2026-07-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0025_hotspot_micro_catchment_villages'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotspot',
            name='unique_active_hotspot_village',
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='village',
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='micro_catchment',
            field=models.ForeignKey(db_column='MicroCatchmentId', on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='location.microcatchment'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='villages',
            field=models.ManyToManyField(blank=True, db_table='tblHotspotVillages', limit_choices_to={'type': 'V'}, related_name='hotspots', to='location.location'),
        ),
        migrations.AlterField(
            model_name='microcatchment',
            name='district',
            field=models.ForeignKey(blank=True, db_column='DistrictId', limit_choices_to={'type': 'R'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='micro_catchments', to='location.location'),
        ),
        migrations.AlterField(
            model_name='microcatchmentgvh',
            name='location',
            field=models.ForeignKey(db_column='LocationId', limit_choices_to={'type': 'W'}, on_delete=django.db.models.deletion.CASCADE, related_name='micro_catchments_gvh', to='location.location'),
        ),
        migrations.AlterField(
            model_name='microcatchmentta',
            name='location',
            field=models.ForeignKey(db_column='LocationId', limit_choices_to={'type': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='micro_catchments_ta', to='location.location'),
        ),
    ]
