# Generated by Django 4.2.26 on 2026-07-03 09:33

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0026_remove_hotspot_unique_active_hotspot_village_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='villages',
        ),
        migrations.CreateModel(
            name='HotspotVillage',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='HotspotVillageId', primary_key=True, serialize=False)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
                ('hotspot', models.ForeignKey(db_column='HotspotId', on_delete=django.db.models.deletion.CASCADE, related_name='village_links', to='location.hotspot')),
                ('location', models.ForeignKey(db_column='LocationId', limit_choices_to={'type': 'V'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_links', to='location.location')),
            ],
            options={
                'db_table': 'tblHotspotVillages',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
    ]
