# Generated by Django 4.2.30 on 2026-08-05 18:40

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0027_remove_hotspot_villages_hotspotvillage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catchment',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='CatchmentId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='CatchmentUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('code', models.CharField(db_column='Code', max_length=50)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblCatchments',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CatchmentDistrict',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='CatchmentDistrictId', primary_key=True, serialize=False)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('catchment', models.ForeignKey(db_column='CatchmentId', on_delete=django.db.models.deletion.CASCADE, related_name='district_links', to='location.catchment')),
                ('location', models.ForeignKey(db_column='LocationId', limit_choices_to={'type': 'R'}, on_delete=django.db.models.deletion.CASCADE, related_name='catchment_links', to='location.location')),
            ],
            options={
                'db_table': 'tblCatchmentDistricts',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='catchment',
            constraint=models.UniqueConstraint(condition=models.Q(('validity_to__isnull', True)), fields=('code',), name='location_unique_active_catchment_code'),
        ),
        migrations.AddConstraint(
            model_name='catchmentdistrict',
            constraint=models.UniqueConstraint(condition=models.Q(('validity_to__isnull', True)), fields=('catchment', 'location'), name='location_unique_active_catchment_district'),
        ),
    ]
